server:
  port: 8888
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    name: seckill
    url: jdbc:mysql://localhost:3306/seckill?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: wxhtobe1
    #使用 druid 数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  #配置springboot对redis的依赖
  redis:
    host: 127.0.0.1
    port: 6379
    database: 10
    #password=
    #设置jedis连接池
    jedis:
      pool:
        max-active: 50
        min-idle: 20

  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

mq:
  nameserver:
   addr: 39.107.152.73:9876
  topicname: stock

#logging:
#  level:
#    com.manster: debug
